apiVersion: v1
kind: Service
metadata:
  name: logs-viewer-web
  namespace: rocketchat
  labels:
    app.kubernetes.io/name: logs-viewer-web
spec:
  selector:
    app.kubernetes.io/name: logs-viewer-web
  ports:
    - name: http
      port: 80
      targetPort: http
