resources:
  - rocketchat-server.yaml
  - rocketchat-mongodb.yaml
  - rocketchat-nats.yaml
  - rocketchat-servicemonitors.yaml
  - prometheus-agent-configmap.yaml
  - prometheus-agent-deployment.yaml
  - prometheus-agent-rbac.yaml
  - maintenance-cleanup.yaml
  - clusterissuer.yaml
  - persistent-volumes.yaml
  - mongo-pvc.yaml
  - rocketchat-uploads-pvc.yaml
  - podmonitor-crd.yaml
