---
# Source: rocketchat/charts/nats/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rocketchat-nats
  namespace: rocketchat
  labels:
    helm.sh/chart: nats-0.15.1
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: rocketchat
    app.kubernetes.io/version: "2.7.4"
    app.kubernetes.io/managed-by: Helm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: rocketchat
---
# Source: rocketchat/charts/nats/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketchat-nats-config
  namespace: rocketchat
  labels:
    helm.sh/chart: nats-0.15.1
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: rocketchat
    app.kubernetes.io/version: "2.7.4"
    app.kubernetes.io/managed-by: Helm
data:
  nats.conf: |
    # NATS Clients Port
    port: 4222

    # PID file shared with configuration reloader.
    pid_file: "/var/run/nats/nats.pid"

    ###############
    #             #
    # Monitoring  #
    #             #
    ###############
    http: 8222
    server_name:$POD_NAME
    ###################################
    #                                 #
    # NATS Full Mesh Clustering Setup #
    #                                 #
    ###################################
    cluster {
      port: 6222

      routes = [
        nats://rocketchat-nats-0.rocketchat-nats.rocketchat.svc.cluster.local:6222,
        
      ]
      cluster_advertise: $CLUSTER_ADVERTISE

      connect_retries: 120
    }
    lame_duck_grace_period: 10s
    lame_duck_duration: 30s
---
# Source: rocketchat/charts/nats/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-nats
  namespace: rocketchat
  labels:
    helm.sh/chart: nats-0.15.1
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: rocketchat
    app.kubernetes.io/version: "2.7.4"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: rocketchat
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
  - name: leafnodes
    port: 7422
  - name: gateways
    port: 7522
---
# Source: rocketchat/templates/nats-monitor.yaml
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-nats-metrics
  namespace: rocketchat
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8222"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: rocketchat
  publishNotReadyAddresses: true
  ports:
  - appProtocol: http
    name: monitor
    port: 8222
    protocol: TCP
    targetPort: monitor
  sessionAffinity: None
---
# Source: rocketchat/charts/nats/templates/nats-box.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-nats-box
  namespace: rocketchat
  labels:
    app: rocketchat-nats-box
    chart: nats-0.15.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-nats-box
  template:
    metadata:
      labels:
        app: rocketchat-nats-box
    spec:
      containers:
      - name: nats-box
        image: natsio/nats-box:0.8.1
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URL
          value: rocketchat-nats
        command:
        - "tail"
        - "-f"
        - "/dev/null"
---
# Source: rocketchat/charts/nats/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketchat-nats
  namespace: rocketchat
  labels:
    helm.sh/chart: nats-0.15.1
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: rocketchat
    app.kubernetes.io/version: "2.7.4"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: rocketchat
  replicas: 1
  serviceName: rocketchat-nats
  podManagementPolicy: Parallel
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "7777"
        prometheus.io/scrape: "true"
        checksum/config: 3629675b28bf88c0504609b8bb05c27ffbe18d21e8474023d82a52e4a195195e
      labels:
        app.kubernetes.io/name: nats
        app.kubernetes.io/instance: rocketchat
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: rocketchat-nats-config
      - name: pid
        emptyDir: {}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: nats
        image: nats:2.4-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        command:
        - "nats-server"
        - "--config"
        - "/etc/nats-config/nats.conf"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_NAME
          value: $(POD_NAME)
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).rocketchat-nats.$(POD_NAMESPACE).svc.cluster.local
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: pid
          mountPath: /var/run/nats
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 30
        lifecycle:
          preStop:
            exec:
              command:
              - "nats-server"
              - "-sl=ldm=/var/run/nats/nats.pid"
      - name: reloader
        image: natsio/nats-server-config-reloader:0.6.3
        imagePullPolicy: IfNotPresent
        command:
        - "nats-server-config-reloader"
        - "-pid"
        - "/var/run/nats/nats.pid"
        - "-config"
        - "/etc/nats-config/nats.conf"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: pid
          mountPath: /var/run/nats
      - name: metrics
        image: natsio/prometheus-nats-exporter:0.9.1
        imagePullPolicy: IfNotPresent
        args:
        - -connz
        - -routez
        - -subz
        - -varz
        - -prefix=nats
        - -use_internal_server_id
        - http://localhost:8222/
        ports:
        - containerPort: 7777
          name: metrics

